# Generated by Django 3.1.13 on 2021-09-13 14:33

from django.db import migrations, models
import qrtable.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrtable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=qrtable.models.get_image_path),
        ),
    ]
