# Generated by Django 3.1.13 on 2021-09-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('qrtable', '0002_qrtable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtable',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
