# Generated by Django 3.1.13 on 2021-09-13 17:30

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
       
    ]
