# Generated by Django 3.1.13 on 2021-09-13 17:30

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_category_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_product_image_path),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_category_image_path),
        ),
    ]
