# Generated by Django 3.1.13 on 2021-09-13 19:17

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210913_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product'),
        ),
    ]
