# Generated by Django 3.1.13 on 2021-09-13 19:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210913_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_plaintext',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
