# Generated by Django 3.2.7 on 2021-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210917_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='casuser',
            name='mobile',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that mobile number already exists.'}, max_length=15, unique=True, verbose_name='mobile number'),
            preserve_default=False,
        ),
    ]
