# Generated by Django 3.2.7 on 2021-09-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_casuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=16)),
            ],
        ),
    ]
