# Generated by Django 3.2.7 on 2021-09-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casuser',
            name='email',
        ),
    ]
